language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t simeonch7/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true simeonch7/docker-react npm run test